site_name: Projeto Integrador de Engenharia 1
repo_name: "Projeto-Integrador-de-Engenharia-1"
repo_url: "https://github.com/JoaoBarreto03/Projeto-Integrador-de-Engenharia-1"

nav:
  - Home: index.md
  - Sobre: about.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Tema claro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Tema escuro
